language: scala
scala:
   - 2.12.3
jdk:
   - oraclejdk8
script:
  - sbt clean coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
webhooks:
  urls:
    - https://webhooks.gitter.im/e/b937dc262240883c8a23
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: never     # options: [always|never|change] default: always